#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
    path: /api/login_check


orders:
    type: rest
    resource: App\Controller\OrderController
    prefix: api